- name: Write nagios check command config.
  tags:
    - nrpe-external-master-relation-changed
  template:
    src: "check_name.cfg.jinja2"
    dest: "/etc/nagios/nrpe.d/{{ check_name }}.cfg"
    owner: nagios
    group: nagios
    mode: 0644
  when: "'nagios_hostname' in current_relation"

- name: Write nagios check service definition for export.
  tags:
    - nrpe-external-master-relation-changed
  template:
    src: "check_name_service_export.cfg.jinja2"
    dest: "/var/lib/nagios/export/service__{{ current_relation['nagios_hostname'] }}_{{ check_name }}.cfg"
    owner: nagios
    group: nagios
    mode: 0644
  when: "'nagios_hostname' in current_relation"

- name: Trigger nrpe-external-master-relation-changed to restart.
  tags:
    - nrpe-external-master-relation-changed
  command: >
    relation-set timestamp={{ ansible_date_time.iso8601_micro }}
  when: "'nagios_hostname' in current_relation"
